
name: Initial Deploy

on:
  workflow_dispatch:
    inputs:
      cloud:
        description: Cloud environment for initial deploy
        required: true
        default: 'all'

jobs:
            
  deploy-azure:
    if: contains(github.event.inputs.cloud, 'azure') || github.event.inputs.cloud == 'all'
    runs-on: ubuntu-latest
    environment:
      name: azure
      url: http://azure.monacloud.mvkaran.net
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Set context from Kubeconfig
        uses: azure/k8s-set-context@v1
        id: setcontext
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }} 
          context: ${{ secrets.CLUSTER_NAME }}          

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml

      - name: Get service ingress IP address
        run: |
            echo "SVC_INGRESS_IP=$(kubectl get svc monacloud-svc -o jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV

      - name: Update Cloudflare DNS records
        uses: rez0n/create-dns-record@v2.1
        with:
          type: "A"
          name: "azure.monacloud.mvkaran.net"
          content: ${{ env.SVC_INGRESS_IP }}
          ttl: 1
          proxied: false
          token: ${{ secrets.CLOUDFLARE_TOKEN }}
          zone: ${{ secrets.CLOUDFLARE_ZONE_ID }}

        

  deploy-aws:
    if: contains(github.event.inputs.cloud, 'aws') || github.event.inputs.cloud == 'all'
    runs-on: ubuntu-latest
    environment:
      name: aws
      url: http://aws.monacloud.mvkaran.net

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set Kubeconfig
        run: |
         aws eks --region ap-south-1 update-kubeconfig --name monacloud 

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml

  deploy-google-cloud:
    if: contains(github.event.inputs.cloud, 'gcp') || github.event.inputs.cloud == 'all'
    runs-on: ubuntu-latest
    environment:
      name: google-cloud
      url: http://gcp.monacloud.mvkaran.net

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Get GKE credentials
        id: get-credentials
        uses: google-github-actions/get-gke-credentials@main
        with:
          cluster_name: monacloud
          location: us-central1
          credentials: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            k8s.yaml
      
